export const demoMarketCodes = [
  {
    'marketCode' : '511T01',
    'name' : '5.11',
    'brandRefCode': 'M7V9',
    'industry' : 'Apparel',
    'manager' : 'Madelyn Kiss',
    'developer' : 'Ben Fung',
    'assistant' : '',
    'advisor' : 'Mike Ho',
  },
  {
    'marketCode' : '511T02',
    'name' : '5.11',
    'brandRefCode': 'M7V1',
    'industry' : 'Pack',
    'manager' : 'Madelyn Kiss',
    'developer' : 'Ben Fung',
    'assistant' : '',
    'advisor' : 'Mike Ho',
  },
  {
    'marketCode' : '511T07',
    'name' : '5.11',
    'brandRefCode': 'M7V2',
    'industry' : 'Military',
    'manager' : 'Madelyn Kiss',
    'developer' : 'Ben Fung',
    'assistant' : '',
    'advisor' : 'Mike Ho',
  },
  {
    'marketCode' : '686T01',
    'name' : '686 Technical Apparel',
    'brandRefCode': 'M7V3',
    'industry' : 'Apparel',
    'manager' : 'Madelyn Kiss',
    'developer' : 'Ting Chu',
    'assistant' : '',
    'advisor' : 'Theresa Zhang',
  },
  {
    'marketCode' : '90PO02',
    'name' : '90 points-90分',
    'brandRefCode': 'M7V4',
    'industry' : 'Pack',
    'manager' : '',
    'developer' : '',
    'assistant' : '',
    'advisor' : '',
  },
  {
    'marketCode' : '90PO99',
    'name' : '90 points-90分',
    'brandRefCode': 'M7V5',
    'industry' : 'Delete',
    'manager' : '',
    'developer' : '',
    'assistant' : '',
    'advisor' : '',
  },
  {
    'marketCode' : 'AARN01',
    'name' : 'Aarn Design Ltd.',
    'brandRefCode': 'M7V6',
    'industry' : 'Apparel',
    'manager' : 'May Wong',
    'developer' : '',
    'assistant' : '',
    'advisor' : '',
  },
  {
    'marketCode' : 'ABBL01',
    'name' : 'AB Blåkläder',
    'brandRefCode': 'M7V7',
    'industry' : 'Apparel',
    'manager' : 'Massimo Andor',
    'developer' : '',
    'assistant' : '',
    'advisor' : '',
},
  {
    'marketCode' : 'ABLE02',
    'name' : 'Able Carry',
    'brandRefCode': 'M7V8',
    'industry' : 'Pack',
    'manager' : '',
    'developer' : 'Alvs Kwong',
    'assistant' : '',
    'advisor' : '',
  },
  {
    'marketCode' : 'ABLE99',
    'name' : 'ABle Carry',
    'brandRefCode': 'M7V9',
    'industry' : 'Delete',
    'manager' : '',
    'developer' : 'Alvs Kwong',
    'assistant' : '',
    'advisor' : '',
  }
]

export const demoTargets = [
  'Custom',
  'General'
]