export const demoPCCExtraInfomations = [
  {
    'id': 1,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'type': 'Mold Charge',
    'detail': 'USD 5000',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 2,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'type': 'Incoterm',
    'detail': 'ex-fty China',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 3,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'type': 'Bulk Leadtime',
    'detail': '28 days',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 4,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'type': 'Bulk Order MOQ',
    'detail': 'No for black',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 5,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'type': 'Bulk Color MOQ',
    'detail': '1000pcs',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 6,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'type': 'Mold Charge',
    'detail': 'HKD 3000',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 7,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'type': 'Incoterm',
    'detail': 'ex-fty China',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 8,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'type': 'Bulk Leadtime',
    'detail': '30 days',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 9,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'type': 'Bulk Order MOQ',
    'detail': '3000PCS; surcharge US$30 if below MOQ',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 10,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'type': 'Mold Charge',
    'detail': 'HKD 4000',
    'remarks': 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 11,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'type': 'Incoterm',
    'detail': 'ex-fty China',
    'remarks': 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 12,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'type': 'Bulk Leadtime',
    'detail': '60 days',
    'remarks': 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 13,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'type': 'Bulk Order MOQ',
    'detail': '5000PCS; surcharge US$50 if below MOQ',
    'remarks': 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  }
]

export const demoPCCPrices = [
  {
    'id': 1,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'season': 'S20',
    'isActive': true,
    'currency': 'USD',
    'value': 0.03,
    'unit': 'PCS',
    'lastUpdated': '01/07/2020',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 2,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'season': 'S21',
    'isActive': true,
    'currency': 'USD',
    'value': 0.05,
    'unit': 'PCS',
    'lastUpdated': '01/07/2021',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 3,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'season': 'S22',
    'isActive': true,
    'currency': 'USD',
    'value': 0.22,
    'unit': 'set',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 4,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'season': 'F22',
    'isActive': true,
    'currency': 'USD',
    'value': 0.22,
    'unit': 'set',
    'lastUpdated': '01/07/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 5,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'season': 'S22',
    'isActive': true,
    'currency': 'HKD',
    'value': 0.1716,
    'unit': 'set',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 6,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'season': 'F22',
    'isActive': true,
    'currency': 'HKD',
    'value': 0.22,
    'unit': 'set',
    'lastUpdated': '01/07/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 7,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'season': 'S22',
    'isActive': true,
    'currency': 'USD',
    'value': 0.32,
    'unit': 'set',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 8,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'season': 'F22',
    'isActive': true,
    'currency': 'USD',
    'value': 0.32,
    'unit': 'set',
    'lastUpdated': '01/07/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 9,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'season': 'S22',
    'isActive': true,
    'currency': 'HKD',
    'value': 0.2716,
    'unit': 'set',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 10,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'season': 'F22',
    'isActive': true,
    'currency': 'HKD',
    'value': 0.32,
    'unit': 'set',
    'lastUpdated': '01/07/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 11,
    'pccId': 3,
    'marketCode': 'LLBE01',
    'brandRefCode': '#1478',
    'season': 'F22',
    'isActive': true,
    'currency': 'HKD',
    'value': 0.32,
    'unit': 'set',
    'lastUpdated': '01/07/2022',
    'lastUpdatedBy': 'Fred Fung',
  }
]

export const demoPCCVendors = [
  {
    'id': 1,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'value': 'XXX Ltd.',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 2,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'value': 'XXX Ltd.',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
]

export const demoPCCUsages = [
  {
    'id': 1,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'value': 'Shoes',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 2,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'value': 'Pack',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
]

export const demoPCCForSales = [
  {
    'id': 1,
    'pccId': 1,
    'marketCode': '511T01',
    'brandRefCode': 'M7V9',
    'newProductName': null,
    'newSizeName': null,
    'remarks': 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 2,
    'pccId': 2,
    'marketCode': 'LLBE01',
    'brandRefCode': '#136097',
    'newProductName': null,
    'newSizeName': null,
    'remarks': 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 3,
    'pccId': 2,
    'marketCode': 'LLBE02',
    'brandRefCode': '#136097',
    'newProductName': null,
    'newSizeName': null,
    'remarks': 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
  {
    'id': 4,
    'pccId': 3,
    'marketCode': 'LLBE01',
    'brandRefCode': '#1478',
    'newProductName': null,
    'newSizeName': '15mm (LLBE)',
    'remarks': 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    'lastUpdated': '01/03/2022',
    'lastUpdatedBy': 'Fred Fung',
  },
]

export const demoVerdors = [
  'XXX Ltd.',
  'YYY Ltd.'
]

export const demoCurrencies = [
  'USD', 'CNY', 'HKD'
]

export const demoUnits = [
  'PCS', 'HPCS', 'set', 'yard'
]

export const demoIncoTerms = [
  'ex-fty China'
]